<?php


namespace AwardWallet\Engine\mileageplus\RewardAvailability;


use AwardWallet\Engine\ProxyList;

class Register extends \TAccountChecker
{
    use ProxyList;
    use \SeleniumCheckerHelper;

    private const XPATH_ALERT = '//div[contains(@id, "alert-")and contains(@id, "-atm-x-autogenerated-id_")]';

    public function InitBrowser()
    {
        parent::InitBrowser();

        $this->useSelenium();
        $this->useFirefox(\SeleniumFinderRequest::FIREFOX_100);
        $this->disableImages();
        $this->http->saveScreenshots = true;


        $this->setProxyNetNut();

        $resolutions = [
            [1152, 864],
            [1280, 720],
            [1280, 768],
            [1280, 800],
            [1360, 768],
            [1366, 768],
        ];

        $this->setScreenResolution($resolutions[array_rand($resolutions)]);
        $this->useCache();
        $this->http->setRandomUserAgent(null, true, false);
    }


    public function getRegisterFields()
    {

        return [
            'FirstName' => [
                'Type' => 'string',
                'Caption' => 'First Name',
                'Required' => true,
            ],
            'LastName' => [
                'Type' => 'string',
                'Caption' => 'Last Name',
                'Required' => true,
            ],
            'Email' => [
                'Type' => 'string',
                'Caption' => 'Email address',
                'Required' => true,
            ],
            'BirthdayDate' => [
                'Type' => 'date',
                'Caption' => 'Your date of birth, older than 18(MM/DD/YYYY)',
                'Required' => true,
            ],
            'Gender' => [
                'Type' => 'string',
                'Caption' => 'Gender',
                'Required' => true,
                'Options' => ['male' => 'Male', 'female' => "Female"],
            ],
            'Country' => [
                'Type' => 'string',
                'Caption' => 'State',
                'Required' => true,
                'Options' => ['CA' => 'Canada']
            ],
            'Address' => [
                'Type' => 'string',
                'Caption' => 'Address',
                'Required' => true,
                'Note' => "Please use only the 26 English letters (A-Z), numerals (0-9), periods (.), hyphens (-), apostrophes ('), number signs (#), and spaces",
            ],
            'City' => [
                'Type' => 'string',
                'Caption' => 'City',
                'Required' => true,
                'Note' => 'Please use only the 26 English letters (A-Z), periods (.), hyphens (-), and spaces.',
            ],
            'State' => [
                'Type' => 'string',
                'Caption' => 'State (US only)',
                'Required' => true,
                'Note' => 'Please use only the 26 English letters (A-Z), periods (.), hyphens (-), and spaces.',
            ],
            'ZipCode' => [
                'Type' => 'string',
                'Caption' => 'Zip Code',
                'Required' => true,
                'Note' => 'Please use only the 26 English letters (A-Z), numerals (0-9), hyphens (-), parentheses ( ), and spaces.',
            ],
            'Password' => [
                'Type' => 'string',
                'Caption' => 'Password',
                'Required' => true,
                'Note' => "Must be at least 8 characters in length.Must include at least one letter and one number. Standard special characters (such as '!' '&' and '+') are optional. Dont use '¡','¿','¨']",
            ],
        ];
    }

    public function registerAccount(array $fields)
    {
        $this->logger->notice(__METHOD__);
        $this->logger->debug(var_export($fields, true), ['pre' => true]);

        $this->checkFields($fields);
        $this->http->GetURL("https://www.united.com/en/us/account/enroll/profile");

        if ($cookieButton = $this->waitForElement(\WebDriverBy::xpath('//a[contains(@class, "cc-btn") and contains(@class, "cc-allow") and contains(@class, "cc-btn-format")]'))) {
            $cookieButton->click();
        }

        $firstName = $this->waitForElement(\WebDriverBy::xpath('//input[@id="enrollment-form-first-name"]'), 20);
        $lastName = $this->waitForElement(\WebDriverBy::xpath('//input[@id="enrollment-form-last-name"]'), 0);
        $monthDate = $this->waitForElement(\WebDriverBy::xpath('//select[contains(@class, "atm-c-select") and contains(@class, "atm-c-select-field__control")][not(@name="enrollment-form.profile.suffix")]'),
            0);
        $dayDate = $this->waitForElement(\WebDriverBy::xpath('//input[@placeholder="DD"]'));
        $yearDate = $this->waitForElement(\WebDriverBy::xpath('//input[@placeholder="YYYY"]'));
        $genderSelect = $this->waitForElement(\WebDriverBy::xpath('//select[@name="enrollment-form.profile.gender"]'),
            0);
        $email = $this->waitForElement(\WebDriverBy::xpath('//input[@id="enrollment-form-email"]'), 0);
        $buttonContinue = $this->waitForElement(\WebDriverBy::xpath('//button[contains(@class, "atm-c-btn") and contains(@class, "atm-c-btn--primary")]/span[text()="Continue"]'),
            0);

        if (!$firstName || !$lastName || !$monthDate ||
            !$dayDate || !$yearDate || !$genderSelect || !$email) {

            $this->saveResponse();
            $this->logger->error('no register form or other format');

            return false;

        }

        $month = $this->getDatePart('m', $fields['BirthdayDate']);
        $month = $this->monthDateSelect($month, $monthDate->getText());

        $gender = $this->genderIdentification($fields['Gender']);

        $firstName->sendKeys($fields['FirstName']);
        $lastName->sendKeys($fields['LastName']);
        $dayDate->sendKeys($this->getDatePart('d', $fields['BirthdayDate']));
        $yearDate->sendKeys($this->getDatePart('Y', $fields['BirthdayDate']));

        $monthDateOption = $this->waitForElement(\WebDriverBy::xpath("//select[contains(@class, 'atm-c-select') and contains(@class, 'atm-c-select-field__control')][not(@name='enrollment-form.profile.suffix')][not(@name='enrollment-form.profile.gender')]/Option[text()='{$month}']"),
            1);
        $this->someSleep();
        $monthDate->click();
        $monthDateOption->click();

        $this->someSleep();
        $genderSelect->sendKeys($gender);
        $email->sendKeys($fields['Email']);
        $this->saveResponse();

        $month = substr($month, 0, 2);
        $registerInfo = [
            "FirstName" => $this->http->FindSingleNode('//input[@id="enrollment-form-first-name"]/@value'),
            "LastName" => $this->http->FindSingleNode('//input[@id="enrollment-form-last-name"]/@value'),
            "BirthdayDate" => "{$month}/{$this->http->FindSingleNode('//input[@placeholder="DD"]/@value')}/{$this->http->FindSingleNode('//input[@placeholder="YYYY"]/@value')}",
            "Gender" => $gender,
            "Email" => $this->http->FindSingleNode('//input[@id="enrollment-form-email"]/@value'),
        ];

        $buttonContinue->click();

        $this->waitFor(function () {
            return $this->waitForElement(\WebDriverBy::xpath('
            //select[@name="enrollment-form.contactInfo.country"]
            | ' . self::XPATH_ALERT), 0);
        }, 30);
        $this->alertChecker();

        $countrySelect = $this->waitForElement(\WebDriverBy::xpath('//select[@name="enrollment-form.contactInfo.country"]'),
            0);
        $addressLine1 = $this->waitForElement(\WebDriverBy::xpath('//input[@id="enrollment-form-address1"]'), 0);
        $addressLine2 = $this->waitForElement(\WebDriverBy::xpath('//input[@id="enrollment-form-address2"]'), 0);
        $city = $this->waitForElement(\WebDriverBy::xpath('//input[@id="enrollment-form-city"]'), 0);
        $state = $this->waitForElement(\WebDriverBy::xpath('//input[@id="enrollment-form-state"]'), 0);
        $ZIP = $this->waitForElement(\WebDriverBy::xpath('//input[@id="enrollment-form-postal-code"]'), 0);
        $buttonContinue = $this->waitForElement(\WebDriverBy::xpath('//button[contains(@class, "atm-c-btn") and contains(@class, "atm-c-btn--primary")]/span[text()="Continue"]'),
            0);

        if (!$countrySelect || !$addressLine1 || !$addressLine2
            || !$city || !$state || !$ZIP || !$buttonContinue) {

            $this->saveResponse();
            $this->logger->error('no register form or other format');

            return false;
        }

        $address = $this->splitAddress($fields["Address"]);

        $countrySelect->click();
        $country = $this->waitForElement(\WebDriverBy::xpath("//select[@name='enrollment-form.contactInfo.country']/option[@value='CA']"),
            2);
        $country->click();
        $addressLine1->sendKeys($address[0]);
        $addressLine2->sendKeys($address[1]);
        $this->saveResponse();

        $city->sendKeys($fields['City']);
        $state->sendKeys($fields['State']);
        $ZIP->sendKeys($fields['ZipCode']);
        $this->saveResponse();

        $registerInfo += [
            "Country" => $country->getText(),
            "Address" => "{$this->http->FindSingleNode('//input[@id="enrollment-form-address1"]/@value')} {$this->http->FindSingleNode('//input[@id="enrollment-form-address2"]/@value')}",
            "City" => $this->http->FindSingleNode('//input[@id="enrollment-form-city"]/@value'),
            "State" => $this->http->FindSingleNode('//input[@id="enrollment-form-state"]/@value'),
            "ZipCode" => $this->http->FindSingleNode('//input[@id="enrollment-form-postal-code"]/@value'),
        ];


        $buttonContinue->click();
        $this->waitFor(function () {
            return $this->waitForElement(\WebDriverBy::xpath('
            //input[@id="enrollment-form-password"]
            | ' . self::XPATH_ALERT), 0);
        }, 30);
        $this->alertChecker();

        $password = $this->waitForElement(\WebDriverBy::xpath('//input[@id="enrollment-form-password"]'), 0);
        $buttonContinue = $this->waitForElement(\WebDriverBy::xpath('//button[contains(@class, "atm-c-btn") and contains(@class, "atm-c-btn--primary")]/span[text()="Agree and create account"]'),
            0);

        if (!$password || !$buttonContinue) {

            $this->saveResponse();
            $this->logger->error('no register form or other format');

            return false;
        }

        $password->sendKeys($fields['Password']);

        $questionAndAnswerArray = [];
        for ($i = 1; $i <= 5; $i++) {

            $questionSelect = $this->waitForElement(\WebDriverBy::xpath("//select[@name='enrollment-form.security.securityQuestions.q{$i}']"),
                1);
            $question = $this->examQuestion($questionSelect->getText());
            $questionSelect->click();
            sleep(2);

            $questionOption = $this->waitForElement(\WebDriverBy::xpath("//select[@name='enrollment-form.security.securityQuestions.q{$i}']/option[text()='{$question}']"),
                1);
            $questionOption->click();
            $this->someSleep();
            $this->saveResponse();


            $answerSelect = $this->waitForElement(\WebDriverBy::xpath("//select[@name='enrollment-form.security.securityAnswers.a{$i}']"),
                0);
            $answer = $this->examAnswer($answerSelect->getText());
            $answerSelect->click();

            $answerOption = $this->waitForElement(\WebDriverBy::xpath("//select[@name='enrollment-form.security.securityAnswers.a{$i}']/Option[text()='{$answer}']"),
                1);
            $answerOption->click();
            $this->someSleep();
            $this->saveResponse();

            $questionAndAnswerArray[] = [
                "question" => $question,
                "answer" => $answer
            ];
        }

        $registerInfo += [
            "Password" => $this->http->FindSingleNode('//input[@id="enrollment-form-password"]/@value'),
        ];

        $buttonContinue = $this->waitForElement(\WebDriverBy::xpath('//button[contains(@class, "atm-c-btn") and contains(@class, "atm-c-btn--primary")]/span[text()="Agree and create account"]'),
            0);
        $buttonContinue->click();

        $this->waitFor(function () {
            return $this->waitForElement(\WebDriverBy::xpath('
            //span[@id="mileagePlusNumber"]
            | ' . self::XPATH_ALERT), 0);
        }, 20);
        $this->alertChecker();

        $mileagePlusNumber = $this->waitForElement(\WebDriverBy::xpath('//span[@id="mileagePlusNumber"]'), 0);
        $this->saveResponse();

        if ($mileagePlusNumber) {
            $this->ErrorMessage = json_encode([
                "status" => "success",
                "message" => "Registration is successful! Membership number: {$mileagePlusNumber->getText()}",
                "login" => $mileagePlusNumber->getText(),
                "login2" => $registerInfo['LastName'],
                "login3" => '',
                "password" => $fields["Password"],
                "email" => $registerInfo["Email"],
                "questions" => $questionAndAnswerArray,
                "registerInfo" => [
                    [
                        "key" => "FirstName",
                        "value" => $registerInfo["FirstName"]
                    ],
                    [
                        "key" => "LastName",
                        "value" => $registerInfo["LastName"],
                    ],
                    [
                        "key" => "BirthdayDate",
                        "value" => $registerInfo["BirthdayDate"],
                    ],
                    [
                        "key" => "Gender",
                        "value" => $registerInfo['Gender'],
                    ],
                    [
                        "key" => "Country",
                        "value" => $registerInfo["Country"],
                    ],
                    [
                        "key" => "Address",
                        "value" => $registerInfo["Address"],
                    ],
                    [
                        "key" => "City",
                        "value" => $registerInfo["City"],
                    ],
                    [
                        "key" => "State",
                        "value" => $registerInfo["State"],
                    ],
                    [
                        "key" => "ZipCode",
                        "value" => $registerInfo["ZipCode"]
                    ],
                ],
                "active" => true,
            ], JSON_PRETTY_PRINT);

            $this->saveResponse();
            return true;
        }

        $this->saveResponse();
        return false;

    }

    protected function checkFields(&$fields)
    {
        if (!filter_var($fields['Email'], FILTER_VALIDATE_EMAIL)) {
            throw new \UserInputError('Email address contains an incorrect format');
        }

        if (preg_match("/[\d*¡!?¿<>\\ºª|\/\·@#$%&.,;=?¿())_+{}\-\[\]\"\^€\$£']/", $fields['FirstName'])) {
            throw new \UserInputError('First Name contains an incorrect symbol');
        }

        if (preg_match("/[\d*¡!?¿<>\\ºª|\/\·@#$%&.,;=?¿())_+{}\-\[\]\"\^€\$£']/", $fields['LastName'])) {
            throw new \UserInputError('Last Name contains an incorrect symbol');
        }

        if ((strlen($fields['Password']) < 8 || strlen($fields['Password']) > 30)
            || !preg_match("/[a-z]/", $fields['Password'])
            || !preg_match("/[0-9]/", $fields['Password']) !== false
            || preg_match("/[%&¡¿¨]/", $fields['Password'])) {
            throw new \UserInputError("Must be at least 8 characters in length.Must include at least one letter and one number. Standard special characters (such as '!' '&' and '+') are optional. Dont use '¡','¿','¨']");
        }
        if (preg_match("/[*¡!?¿<>\\ºª|\/\·@$%&№,;=?¿())_+{}\[\]\"\^€\$£]/", $fields['Address'])) {
            throw new \UserInputError('Address Line contains an incorrect symbol');
        }
        if (preg_match("/[\d*¡!?¿<>\\ºª|\/\·@$%&№,;=?¿())_+{}\[\]\"\^€\$£]/", $fields['City'])) {
            throw new \UserInputError('City contains an incorrect symbol');
        }
        if (preg_match("/[\d*¡!?¿<>\\ºª|\/\·@$%&№,;=?¿())_+{}\[\]\"\^€\$£]/", $fields['State'])) {
            throw new \UserInputError('State contains an incorrect symbol');
        }
        if (preg_match("/[*¡!?¿<>\\ºª|\/\·@$%&№,;=?¿_+{}\[\]\"\^€\$£]/", $fields['ZipCode'])) {
            throw new \UserInputError('Zip Code contains an incorrect symbol');
        }
    }

    private function someSleep()
    {
        usleep(random_int(12, 25) * 100000);
    }

    private function getDatePart(string $part, string $date): string
    {
        $dateTime = \DateTime::createFromFormat('m/d/Y', $date);

        return $dateTime->format($part);
    }

    private function monthDateSelect(string $month, string $monthFromSite): string
    {
        $months = explode("\n", $monthFromSite);
        if ($month < 10) {
            return $months[substr($month, 1)];
        } else {
            return $months[$month];
        }
    }

    private function examQuestion(string $questionsFromSite): string
    {
        $questions = explode("\n", $questionsFromSite);
        array_shift($questions);

        $filteredQuestions = array_filter($questions, function ($question) {
            return !str_contains($question, "'");
        });

        $question = $filteredQuestions[array_rand($filteredQuestions)];
        return $question;
    }

    private function examAnswer(string $answerFromSite): string
    {
        $answers = explode("\n", $answerFromSite);
        array_shift($answers);

        $filteredAnswers = array_filter($answers, function ($question) {
            return !str_contains($question, "'");
        });

        $answer = $filteredAnswers[array_rand($filteredAnswers)];
        return $answer;
    }

    private function alertChecker(): void
    {
        if ($alert = $this->waitForElement(\WebDriverBy::xpath('//div[contains(@id, "alert-")and contains(@id, "-atm-x-autogenerated-id_")]'),
            0)) {

            $this->saveResponse();
            $this->logger->error($alert->getText());
            throw new \ProviderError($alert->getText() . '  Please check the entered data');
        }
    }

    private function splitAddress(string $address): array
    {
        if (strlen($address) > 20) {
            $middle = floor(strlen($address) / 2);
            $leftSpace = strrpos(substr($address, 0, $middle), ' ');
            $rightSpace = strpos($address, ' ', $middle);

            if ($leftSpace === false) {
                $splitPos = $rightSpace;
            } elseif ($rightSpace === false) {
                $splitPos = $leftSpace;
            } else {
                $splitPos = ($middle - $leftSpace <= $rightSpace - $middle) ? $leftSpace : $rightSpace;
            }

            if ($splitPos === false) {
                $splitPos = $middle;
            }

            $line1 = substr($address, 0, $splitPos);
            $line2 = substr($address, $splitPos + 1);

            return [$line1, $line2];
        }
        return [$address, ''];
    }

    private function genderIdentification(string $gender): string
    {
        switch ($gender) {
            case 'male':
                return 'M';
            case 'female':
                return 'F';
            default :
                return 'Unspecified';
        }
    }
}