#!/bin/sh

echo "php-cs-fixer pre commit hook start"

FILES=` git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | tr '\n' ' '`
if [ -z "$FILES" ]
then
    echo "php files not found."
else
    docker-compose run --rm -T cs-fixer fix --config=.php-cs-fixer.dist.php --using-cache=no --verbose ${FILES}
    git add ${FILES}
fi

echo "php-cs-fixer pre commit hook finish"
